### ISSUE TITLE
Preserve order of issues

### ISSUE THREAD

**Issue by safaorhan** [code413/issue-duplicator#16]
### Background

Hey, firstly I want to thank you for such a pain-killer app.

I am a tech educator and was looking for ways of creating template repositories (with code + issues) to use them as educational material. That way I can easily duplicate a full project for each of my students.

This app is the closest to what I was looking for so far.

### Problem

Everything runs smoothly but I realized the order of the issues are not preserved when being duplicated from one repo to another.

My assumption is all copy requests are done in parallel and hence the order of the issues are not guaranteed / determined.

The order of issues are important for me each of the issues is an assignment and must be completed in a determined order.

### Proposal

We can create an option which may read something like: "Keep order of issues (may take longer to complete)" and run the requests one by one, to preserve the order of newly created issues.

What do you think?

**Comment by matt-daneshvar** [comment]
Hi Ahmet - Thanks for using the duplicator and for pointing out this issue. 

We actually fetch and re-create issues sequentially. From a quick look at [Github Docs](https://docs.github.com/en/rest/reference/issues), I think the fix should be as simple as changing the sort `direction` when we retrieve the issues. Let me try this and get back to you soon.

**Comment by matt-daneshvar** [comment]
@safaorhan I have pushed up a change that should do the trick. Here's the result of a test I just did: 

![image](https://user-images.githubusercontent.com/10030505/123619177-828ed180-d83b-11eb-8f43-c4a62f020458.png)

Can you double check and see if it works for you too?

**Comment by safaorhan** [comment]
Hey @matt-daneshvar sorry for my late response and thanks for implementing this really quickly, I will try and let you know!

**Comment by safaorhan** [comment]
I tried and it works!

Thanks!
